import type { Metadata } from "next";
import { SlideProvider } from "@/context/SlideContext";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
      >
        <SlideProvider>
        {children}
        </SlideProvider>
      </body>
    </html>
  );
}
